# Generated by Django 3.2.4 on 2021-06-06 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='meal', max_length=200)),
                ('desc', models.CharField(default='A dish', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='meal', max_length=200)),
                ('desc', models.CharField(default='A dish', max_length=600)),
                ('terms1', models.CharField(default='terms', max_length=200)),
                ('terms2', models.CharField(default='terms', max_length=200)),
                ('terms3', models.CharField(default='terms', max_length=200)),
                ('terms4', models.CharField(default='terms', max_length=200)),
                ('src', models.CharField(default='Image', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Room', max_length=200)),
                ('type', models.CharField(default='Single', max_length=200)),
                ('avaliable', models.BooleanField(default=True)),
                ('src', models.CharField(default='Image', max_length=600)),
                ('desc', models.CharField(default='A room', max_length=600)),
                ('price', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
